nohup mooncake_master --port 61088 \
  --eviction_high_watermark_ratio 0.95 \
  --eviction_ratio 0.05 \
  --metrics_port 10003 \
  --enable_http_metadata_server 1 \
  --http_metadata_server_port 61001 \
  --alsologtostderr=false \
  --log_dir=/root/autodl-tmp/pxy/log/ \
  --logtostderr=false \
  --minloglevel=0 \
  --v=3 \ &